project_id = "xeptffxoauvezgbyxnwc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[functions.process-file-with-gemini]
verify_jwt = false