// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeptffxoauvezgbyxnwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlcHRmZnhvYXV2ZXpnYnl4bndjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzkxNDcsImV4cCI6MjA3MjgxNTE0N30.xZ7b0lWCctTmOXNDUQblp-qq6aQc28GZbjfFcrGKVPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});